import {
  Inter,
  Poppins,
  JetBrains_Mono,
  Playfair_Display,
} from "next/font/google";
import "./globals.css";
import SmoothScrollProvider from "@/components/lenis/SmoothScrollProvider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Zonomo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="relative">
      <head />
      <body
        className={`
          ${inter.variable}
          antialiased
        `}
      >
        <SmoothScrollProvider>{children}</SmoothScrollProvider>
      </body>
    </html>
  );
}
